from __future__ import annotations

from pathlib import Path

from PIL import Image

from curate_vision.schema import ImageItem


def _coco_format(items: list[ImageItem]) -> dict:
    """Build a COCO detection annotation JSON from included items."""
    images, annotations = [], []
    ann_id = 1
    for item in items:
        img_id = len(images) + 1
        images.append(
            {
                "id": img_id,
                "file_name": str(item.path),
                "width": item.width,
                "height": item.height,
            }
        )
        # No ground-truth boxes are generated by a curation tool; we emit
        # a single placeholder bbox filling the image so annotation counts
        # stay consistent for external labeling pipelines.
        annotations.append(
            {
                "id": ann_id,
                "image_id": img_id,
                "category_id": 1,
                "bbox": [0.0, 0.0, float(item.width), float(item.height)],
                "area": float(item.width * item.height),
                "iscrowd": 0,
            }
        )
        ann_id += 1
    return {
        "images": images,
        "annotations": annotations,
        "categories": [{"id": 1, "name": "object", "supercategory": "object"}],
    }


def _yolo_txt(item: ImageItem) -> str:
    """Whitespace-normalised YOLO-style line (class 0, full-image box)."""
    return "0 0.5 0.5 1.0 1.0\n"


def export_json_manifest(items: list[ImageItem], out_path: Path) -> Path:
    """Write a JSONL manifest of all items (kept and dropped)."""
    import json

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        for item in items:
            f.write(
                json.dumps(item.to_dict(), ensure_ascii=False, separators=(",", ":"))
                + "\n"
            )
    return out_path


def export_coco_json(items: list[ImageItem], out_path: Path) -> Path:
    """Write COCO JSON for included, non-duplicate items."""
    kept = [i for i in items if i.included and not i.duplicate_of]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    import json

    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(_coco_format(kept), f, ensure_ascii=False, indent=2)
    return out_path


def export_yolo_txt(items: list[ImageItem], labels_dir: Path) -> Path:
    """Write one YOLO label file (`.txt`) per included item."""
    labels_dir.mkdir(parents=True, exist_ok=True)
    written = 0
    for item in items:
        if not item.included or item.duplicate_of:
            continue
        txt = labels_dir / (item.path.stem + ".txt")
        txt.write_text(_yolo_txt(item), encoding="utf-8")
        written += 1
    return labels_dir


def export_hf_dataset(
    items: list[ImageItem],
    out_dir: Path,
) -> Path:
    """Export included items as a HuggingFace dataset (Arrow).

    Requires the optional ``datasets`` extra.
    """
    try:
        from datasets import Dataset, Features, Value
        from datasets import Image as HFImage
    except ImportError as exc:  # pragma: no cover
        raise RuntimeError(
            "HuggingFace export requires the optional dependency.\n"
            "Install with: pip install 'curate-vision[datasets]'"
        ) from exc

    kept = [i for i in items if i.included and not i.duplicate_of]
    data = {
        "image": [str(i.path) for i in kept],
        "path": [str(i.path) for i in kept],
        "width": [i.width for i in kept],
        "height": [i.height for i in kept],
        "phash": [i.phash for i in kept],
    }
    features = Features(
        {
            "image": HFImage(),
            "path": Value("string"),
            "width": Value("int32"),
            "height": Value("int32"),
            "phash": Value("string"),
        }
    )
    ds = Dataset.from_dict(data, features=features)
    out_dir.mkdir(parents=True, exist_ok=True)
    ds.save_to_disk(str(out_dir))
    return out_dir


def export_images(
    items: list[ImageItem],
    out_dir: Path,
) -> None:
    """Copy included images (syminked by default) into an output folder."""
    out_dir.mkdir(parents=True, exist_ok=True)
    for item in items:
        if not item.included or item.duplicate_of:
            continue
        dest = out_dir / item.path.name
        if not dest.exists():
            try:
                dest.symlink_to(item.path)
            except OSError:
                Image.open(item.path).save(dest)


__all__ = [
    "export_json_manifest",
    "export_coco_json",
    "export_yolo_txt",
    "export_hf_dataset",
    "export_images",
]
